export const States = {
  states: [
    {
      name: 'Assam',
      capital: 'Dispur',
      largest_city: 'Guwahati',
      cities: [
        'Guwahati',
        'Silchar',
        'Dibrugarh',
        'Jorhat',
        'Nagaon',
        'Tezpur',
        'Tinsukia',
        'Bongaigaon',
      ],
    },
    {
      name: 'Andhra Pradesh',
      capital: 'Amaravati',
      largest_city: 'Visakhapatnam',
      cities: [
        'Amaravati',
        'Visakhapatnam',
        'Vijayawada',
        'Guntur',
        'Nellore',
        'Tirupati',
        'Kurnool',
        'Rajahmundry',
        'Kakinada',
        'Anantapur',
      ],
    },
    {
      name: 'Karnataka',
      capital: 'Bengaluru',
      largest_city: 'Bengaluru',
      cities: [
        'Bengaluru',
        'Mysuru',
        'Hubballi-Dharwad',
        'Mangalore',
        'Belgaum',
        'Davangere',
        'Ballari',
        'Tumakuru',
        'Shimoga',
        'Bidar',
      ],
    },
    {
      name: 'Maharashtra',
      capital: 'Mumbai',
      largest_city: 'Mumbai',
      cities: [
        'Mumbai',
        'Pune',
        'Nagpur',
        'Nashik',
        'Thane',
        'Aurangabad',
        'Solapur',
        'Jalgaon',
        'Kolhapur',
        'Amravati',
      ],
    },
    {
      name: 'Tamil Nadu',
      capital: 'Chennai',
      largest_city: 'Chennai',
      cities: [
        'Chennai',
        'Coimbatore',
        'Madurai',
        'Tiruchirappalli',
        'Salem',
        'Tirunelveli',
        'Tiruppur',
        'Vellore',
        'Thoothukudi',
        'Dindigul',
      ],
    },
    {
      name: 'Uttar Pradesh',
      capital: 'Lucknow',
      largest_city: 'Kanpur',
      cities: [
        'Lucknow',
        'Kanpur',
        'Ghaziabad',
        'Agra',
        'Meerut',
        'Varanasi',
        'Prayagraj',
        'Bareilly',
        'Aligarh',
        'Moradabad',
      ],
    },
    {
      name: 'West Bengal',
      capital: 'Kolkata',
      largest_city: 'Kolkata',
      cities: [
        'Kolkata',
        'Howrah',
        'Durgapur',
        'Asansol',
        'Siliguri',
        'Bardhaman',
        'Malda',
        'Kharagpur',
        'Darjeeling',
        'Haldia',
      ],
    },
    {
      name: 'Arunachal Pradesh',
      capital: 'Itanagar',
      largest_city: 'Itanagar',
      cities: [
        'Itanagar',
        'Tawang',
        'Ziro',
        'Pasighat',
        'Bomdila',
        'Aalo',
        'Tezu',
        'Namsai',
      ],
    },
    
    {
      name: 'Manipur',
      capital: 'Imphal',
      largest_city: 'Imphal',
      cities: [
        'Imphal',
        'Thoubal',
        'Bishnupur',
        'Churachandpur',
        'Ukhrul',
        'Senapati',
        'Tamenglong',
        'Moreh',
      ],
    },
    {
      name: 'Meghalaya',
      capital: 'Shillong',
      largest_city: 'Shillong',
      cities: [
        'Shillong',
        'Tura',
        'Nongpoh',
        'Jowai',
        'Nongstoin',
        'Mairang',
        'Baghmara',
        'Williamnagar',
      ],
    },
    {
      name: 'Mizoram',
      capital: 'Aizawl',
      largest_city: 'Aizawl',
      cities: [
        'Aizawl',
        'Lunglei',
        'Saiha',
        'Champhai',
        'Serchhip',
        'Kolasib',
        'Lawngtlai',
        'Mamit',
      ],
    },
    {
      name: 'Nagaland',
      capital: 'Kohima',
      largest_city: 'Dimapur',
      cities: [
        'Kohima',
        'Dimapur',
        'Mokokchung',
        'Tuensang',
        'Mon',
        'Wokha',
        'Zunheboto',
        'Phek',
      ],
    },
    {
      name: 'Sikkim',
      capital: 'Gangtok',
      largest_city: 'Gangtok',
      cities: [
        'Gangtok',
        'Namchi',
        'Geyzing',
        'Mangan',
        'Pelling',
        'Ravangla',
        'Jorethang',
        'Singtam',
      ],
    },
    {
      name: 'Tripura',
      capital: 'Agartala',
      largest_city: 'Agartala',
      cities: [
        'Agartala',
        'Udaipur',
        'Dharmanagar',
        'Kailashahar',
        'Belonia',
        'Ambassa',
        'Khowai',
        'Sonamura',
      ],
    },
  ],
};
