export const Vehicledata = [
  {label: 'Car', value: '1'},
  {label: 'MotorCycle', value: '2'},
  {label: 'Scooty', value: '3'},
  {label: 'Bike', value: '4'},
 ];
export const modelData = [
  {
    label: 'Car',
    value: '1',
    models: [
      'BMW',
      'Ford',
      'Fiat',
      'Honda',
      'Hyundai',
      'Jeep',
      'Mercedes',
      'Toyota',
      'Maruti Suzuki',
      'Tata Motors',
      'Mahindra',
      'Renault',
      'Volkswagen',
      'Audi',
      'All Brands',
    ],
  },
  {
    label: 'MotorCycle',
    value: '2',
    models: [
      'Bajaj',
      'Hero',
      'Honda',
      'TVS',
      'Royal Enfield',
      'Suzuki',
      'Yamaha',
      'KTM',
      'Harley-Davidson',
      'Kawasaki',
      'All Brands',
    ],
  },
  {label: 'Scooty', value: '3', models: ['Honda', 'TVS', 'Suzuki', 'Yamaha']},
  {
    label: 'Bike',
    value: '4',
    models: [
      'Bajaj',
      'Hero',
      'Honda',
      'TVS',
      'Royal Enfield',
      'Suzuki',
      'Yamaha',
      'KTM',
      'Harley-Davidson',
      'Kawasaki',
      'All Brands',
    ],
  },
];
export const Fueldata = [
  {label: 'Petrol', value: '1'},
  {label: 'Diesel', value: '2'},
  {label: 'CNG', value: '3'},
  {label: 'LPG', value: '4'},
  {label: 'Electric', value: '5'},
  {label: 'Hybrid', value: '6'},
];
